In [1]:
import numpy as np

In [2]:
A = np.array([4, 1, 3, 2]) ##1

In [3]:
A = np.arange(0,100,10) ##2

In [4]:
A = np.linspace(0,1,11) ##3

In [5]:
A = np.array([3, -2, 4]) ##4
B = A<0
B

array([False,  True, False])

In [6]:
data = np.array([24,57,76,2,79,59,71,75,51,20,93,6,9,58,98,84,0,33,46,60,15,89,48,94,37,42,18,32,49,72]) ##5
np.sort(data)

array([ 0,  2,  6,  9, 15, 18, 20, 24, 32, 33, 37, 42, 46, 48, 49, 51, 57,
       58, 59, 60, 71, 72, 75, 76, 79, 84, 89, 93, 94, 98])

In [7]:
np.argmin(data) ##6

16

In [8]:
np.flip(np.sort(data)).copy() ##7

array([98, 94, 93, 89, 84, 79, 76, 75, 72, 71, 60, 59, 58, 57, 51, 49, 48,
       46, 42, 37, 33, 32, 24, 20, 18, 15,  9,  6,  2,  0])

In [9]:
np.sum(np.sort(data)[0:3]) ##8

8

In [10]:
np.sum(np.argsort( data )[0:3]) ##9

30

In [11]:
subset = np.array([17,64,42,59,54,27,56,30,61,24,94,96,64,85,0]) ##11
np.sum(data[np.isin(data, subset)])

219

In [12]:
SSE = np.sum( (y-a-b*x)**2 ) ##12

NameError: name 'y' is not defined

In [13]:
data.shape ##13
np.sum( data[np.arange(0,30,2)] ) 

714

In [14]:
np.sum(data[data%2==0]) ##14

780

In [19]:
#np.sum(data[data>10 & data<20])
#np.all(10<data<20)
#np.sum( data[np.isin(data[data<20], data[data>10])] )
#data[np.isin(data[data<20], data[data>10])]

15+18+20

53

In [33]:
ham = np.loadtxt("Hamlet.txt", dtype='str') #[13645:13907]
np.sum(np.isin(ham,"nature"))

14